services:
  mt5:
    build: .
    image: ${{ secrets.DOCKERHUB_USERNAME }}/exness-mt5-vnc
    container_name: mt5
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
    env_file:
      - .env

